# Generated by Django 3.1.4 on 2020-12-10 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productShop',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
